version: '3.4'

services:
  dockerdemoapi:
    image: workdemo/dockerdemoapi
    build: ./DockerDemo.Api
    ports: 
      - 8000:80
  
  dockerdemoweb:
    image: workdemo/dockerdemoweb
    build: ./DockerDemo.Web
    ports:
      - 8001:80
    depends_on:
      - dockerdemoapi